name = "BenchmarkPlots"
uuid = "ab8c0f59-4072-4e0d-8f91-a91e1495eb26"
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
BenchmarkTools = "1"
RecipesBase = "1"
julia = "1"
